# **Numpy Task**

EXERCISE 1 - Element-wise addition of 2 numpy arrays
Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar
Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

EXERCISE 3 - Identity Matrix
Create an identity matrix of dimension 4-by-4

EXERCISE 4 - Array re-dimensioning
Convert a 1-D array to a 3-D array

EXERCISE 5 - Array datatype conversion
Convert all the elements of a numpy array from float to integer datatype

EXERCISE 6 - Obtaining Boolean Array from Binary Array
Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

EXERCISE 7 - Horizontal Stacking of Numpy Arrays
Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

EXERCISE 8 - Vertically Stacking of Numpy Arrays
Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

EXERCISE 9 - Custom Sequence Generation
Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

EXERCISE 10 - Getting the positions (indexes) where elements of 2 numpy arrays match
From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

EXERCISE 11 - Generation of given count of equally spaced numbers within a specified range
Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

EXERCISE 12 - Matrix Generation with one particular value
Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

EXERCISE 13 - Array Generation by repeatition of a small array across each dimension
Output an array by repeating a smaller array of 2 dimensions, 10 times

EXERCISE 14 - Array Generation of random integers within a specified range
Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

EXERCISE 15 - Array Generation of random numbers following normal distribution
Output a 3-by-3 array of random numbers following normal distribution

EXERCISE 16 - Matrix Multiplication
Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

EXERCISE 17 - Matrix Transpose
Output the transpose of a matrix (as numpy array)

EXERCISE 18 - Sine of an Angle (in radians)
Calculate the sine of an array of angles (in radians) using NumPy

EXERCISE 19 - Cosine Similarity
Calculate the cosine similarity of 2 vectors (as numpy arrays)

EXERCISE 20 - Generating the array element indexes such that the array elements appear in ascending order

In [1]:
import numpy as np

#1
print("\nEXERCISE 1")
x = np.array([1,2,4,5])
y = np.array([1,4,5,6])
z = x + y
print(z)

#2 
print("\nEXERCISE 2")
y = np.array([[1,2],[3,4]]) * 2
print(y)

#3 
print("\nEXERCISE 3")
eye = np.eye(4)
print(eye)

#4
print("\nEXERCISE 4")
arr = np.array([2,2,2])
arr = arr.reshape(3,1,1)
print(arr)

#5 
print("\nEXERCISE 5")
arr2 = np.array([3,4,5])
print(arr2)
arr2 = arr2.astype(float)
print(arr2)

#6 
print("\nEXERCISE 6")
arr3 = np.eye(5)
arr3 = arr3.astype(bool)
print(arr3)

#7
print("\nEXERCISE 7")
arr4 = np.array([[1,2,3,4]])
arr5 = np.array([[5,6,7,8]])
arr6 = np.hstack((arr4,arr5))
print(arr6)

#8
print("\nEXERCISE 8")
arr7 = np.vstack((arr4,arr5))
print(arr7)

#9
print("\nEXERCISE 9")
arr8 = np.arange(0,102,2)
print(arr8)

#10 
print("\nEXERCISE 10")
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,4,3],[2,5,6]])
match = (a == b)
for i, val in np.ndenumerate(match):
    if val == 1:
        print(f"Values match at index:{i}")

#11 
print("\nEXERCISE 11")
arr9 = np.linspace(0,100,5)
print(arr9)

#12
print("\nEXERCISE 12")
arr10 = np.full((2,3), fill_value=5)
print(arr10)

#13 
print("\nEXERCISE 13")
arr11 = np.tile(arr10,(1,3))
print(arr11)

#14
print("\nEXERCISE 14")
arr12 = np.random.randint(0,10,size=(5,5))
print(arr12)

#15
print("\nEXERCISE 15")
arr13 = np.random.randn(3,3)
print(arr13)

#16
print("\nEXERCISE 16")
arr14 = np.random.randint(0,100,size=(3,3))
arr15 = np.random.randint(0,100,size=(3,3))
print(f'Array 1: \n{arr14}\nArray 2: \n{arr15}')
print(f'Multiplied: \n{np.multiply(arr14,arr15)}')

#17
print("\nEXERCISE 17")
arr14 = np.transpose(arr14)
print(arr14)

#18
print("\nEXERCISE 18")
arr16 = np.random.uniform(0,180,(3,3))
print(arr16)
arr16 = np.sin(arr16)
print(arr16)

#19 
print("\nEXERCISE 19")
A = np.array([1,2,4])
B = np.array([2,4,6])
Cos_Sim = np.dot(A,B) / (np.linalg.norm(A) * np.linalg.norm(B))
print(f"Cosine Similarity: {Cos_Sim}")

#20 
print("\nEXERCISE 20")
C = np.array([2,3,1,5,6,0])
indices = np.argsort(C)
print(C[indices])



EXERCISE 1
[ 2  6  9 11]

EXERCISE 2
[[2 4]
 [6 8]]

EXERCISE 3
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

EXERCISE 4
[[[2]]

 [[2]]

 [[2]]]

EXERCISE 5
[3 4 5]
[3. 4. 5.]

EXERCISE 6
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]

EXERCISE 7
[[1 2 3 4 5 6 7 8]]

EXERCISE 8
[[1 2 3 4]
 [5 6 7 8]]

EXERCISE 9
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]

EXERCISE 10
Values match at index:(0, 0)
Values match at index:(0, 2)
Values match at index:(1, 1)
Values match at index:(1, 2)

EXERCISE 11
[  0.  25.  50.  75. 100.]

EXERCISE 12
[[5 5 5]
 [5 5 5]]

EXERCISE 13
[[5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]]

EXERCISE 14
[[1 8 2 4 0]
 [7 0 6 3 0]
 [3 3 1 1 3]
 [2 8 4 0 4]
 [4 0 5 0 2]]

EXERC